name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update composer
      uses: php-actions/composer@v6
      with:
        version: "2.2.21"
        php_version: "5.6.40"
        command: composer update
    - name: PHPUnit Tests
      uses: php-actions/phpunit@v5
      with:
        php_extensions: "xdebug"
        coverage_html: "coverage/html.xml"
        bootstrap: vendor/autoload.php
        args: --coverage-html
